### PR TITLE
IPv4

### PR DESCRIPTION
**Pull request by GeekMasher**
This is a pattern to find any IPv4 addresses. This will have a semi-high False Positive rate due to not looking for "internal" or specified IP ranges. This pattern will come in the future.

#14

### CODE REVIEW

**Comment by GeekMasher** [comment]
False Positive:

```
"1.1.1.1"
```

This highlights `"1.1.1.1` (includes the quote)

**Review by aegilops — CHANGES_REQUESTED** [review]
You can do better than just `[0-9]`: how about...

```
^((25[0-5]|(2[0-4]|1[0-9]|[1-9]|)[0-9])\.){3}(25[0-5]|(2[0-4]|1[0-9]|[1-9]|)[0-9])$
```

and before and after it, we have `[^0-9.]` to prevent hitting on longer strings of numbers and dots.

**Comment by aegilops** [comment]
IP addresses in the context of URLs can be a broader range of weird cases, and you can also shorten IPs in some other cases, e.g. try `ping 127.1` to see what happens.

**Comment by aegilops** [comment]
https://www.trustwave.com/en-us/resources/blogs/spiderlabs-blog/evasive-urls-in-spam/

**Review by aegilops — APPROVED** [review]

**Comment by aegilops** [comment]
@GeekMasher, before we merge, I want to discuss the NOT matches I added.

I'm trying not to hit on things that will be configured company IP address, so remove things such as localhost, multicast, broadcast and "all interfaces" addresses:

        # listening to everything
        - ^0\.0\.0\.0$
        # localhost
        - ^127\..*
        # example IP ranges - TEST-NET-1, etc.
        - ^192\.0.2\.
        - ^198\.51\.100\.
        - ^203\.0\.113\.
        - ^233\.252\.0\.
        # link local
        - ^169\.254\.
        # multicast
        - ^224\.0\.0\.
        # broadcast
        - ^255\.255\.255\.255$

**Comment by aegilops** [comment]
I don't understand what's happening with the `__snapshots__/any_ipv4_addresses.csv` file at all.

It told me there was a line missing, so I removed it, and now it's telling me the opposite and failing as well.

I don't know what the lines are telling me and what to do to correct it.

**Pull request merged**
