### PR TITLE
added pattern for gh actions sha checker

### PR DESCRIPTION
**Pull request by tjsingh85**
Tested this with @aegilops. Working as expected. able to flag all gh actions not using sha commit

### CODE REVIEW

**Review by aegilops — CHANGES_REQUESTED** [review]
Please can you adjust the pattern to:

```
[a-z0-9_-]{1,39}\/[a-z0-9_-]{1,100}@[a-z0-9._-]{1,39}
```

and the before match to:

```
\buses:[ \t]{1,5}
```

I tested that, and it compiles and works in a test and dry-run.

You'll also need to generate the links in the top-level `README.md`, and use this script to generate that `README.md` instead of (I think?) doing it by hand (which is OK, but Mathew wrote a script for it).

How to do that isn't documented, but you run the [`secretscanning`](https://github.com/advanced-security/secret-scanning-tools/tree/main/secretscanning) python module here, with the right settings.

Clone the repo, install the undocumented requirements:

```
python3 -mpip install pyyaml requests ratelimit jinja2 --user
```

Then run it on the custom patterns dir:
```
python3 -msecretscanning --github-repository=advanced-security/secret-scanning-custom-patterns --markdown -p ~/Repos/secret-scanning-custom-patterns
```

**Comment by tjsingh85** [comment]
@aegilops Made requested changes and updated the top-level Read Me as well. I don't have access to that secret scanning module so update the read-me manually. Hope that's not an issue

**Review by aegilops — APPROVED** [review]
Looks fine to me. In future we'll use the script to edit the Markdown, but it looks OK to me and next time the script is run and the result pushed it'll overwrite it anyway

**Comment by tjsingh85** [comment]
@aegilops Do you know why this job is failing ?

**Comment by aegilops** [comment]
Yes, am bypassing

**Pull request merged**
