### PR TITLE
Removed extra parts in character classes

### PR DESCRIPTION
**Pull request by aegilops**
Removed extra A in character class and leading part before fQ.

The A wasn't needed (it was an error, but not one that would cause FNs).

The leading part before the fQ added nothing to detection of the trailing `}`, so could be removed without problems.

### CODE REVIEW

**Comment by aegilops** [comment]
I realise I should run the script to create the Markdown

**Comment by aegilops** [comment]
This should be ready to merge now @GeekMasher

**Review by GeekMasher — COMMENTED** [review]
@aegilops Is the [template.md](https://github.com/advanced-security/secret-scanning-custom-patterns/blob/main/.github/scripts/template.md) being updated too?

**Review by GeekMasher — APPROVED** [review]
All the changed looks good

**Pull request merged**
