### PR TITLE
fix: internal email pattern regex

### PR DESCRIPTION
**Pull request by timmeinerzhagen**
Custom patterns do not seem to support `\Z` (uppercase) but `\z` (lowercase) seems to work.

image

### CODE REVIEW

**Comment by aegilops** [comment]
Thanks for the spot and the PR!

I just checked on GitHub Cloud, I get that message too, so I'll go ahead and merge, since this doesn't seem to affect the behaviour of the rule.

P.S. It's puzzling to me why this is happening.

It is listed [in the Hyperscan docs as a supported construct](https://intel.github.io/hyperscan/dev-reference/compilation.html#supported-constructs):

> The anchors `^`, `$`, `\A`, `\Z` and `\z`.

I believe it _used_ to work.

**Review by aegilops — CHANGES_REQUESTED** [review]
We also need to adjust the `patterns.yml` file. Can you go that file and change the equivalent `\Z` to `\z` and commit it? I'll be able to merge then.

**Comment by timmeinerzhagen** [comment]
@aegilops updated the yml file as well

**Review by aegilops — APPROVED** [review]
Thank you

**Pull request merged**
