### PR TITLE
IBAN

### PR DESCRIPTION
**Pull request by GeekMasher**

### CODE REVIEW

**Review by NickLiffen — APPROVED** [review]

**Comment by aegilops** [comment]
Let's not merge this yet - I'm making a couple of changes to the pattern

**Comment by aegilops** [comment]
I think this is ready to merge.

**I haven't updated the actual secret scanning pattern on here yet, so the snapshots might change when I do.**

I have now:
* updated the `README.md`!
* updated the generic IBAN rule to remove some FNs I was seeing
* added country-specific patterns using a script to generate them from the HTML on `iban.com`
* added that script, with an option to generate "test" keys when the validator supports that
  * that's for the uploader
* checked these offline using my testing script to hunt for FPs
  * we still get some, e.g. on hexdumps, but they are minimised
  * if FPs are too much, folk can use country-specific versions instead
* confirmed it finds all of the patterns on the `iban.com` page

**Comment by aegilops** [comment]
I added the current version of the IBAN pattern to the Secret Scanning Settings of this repo, so it will be possible to match against `__snapshots__` now.

Everything in the dry-run looked reasonable to me!

**Comment by aegilops** [comment]
I've done even more to remove FPs in real use.

* used some NOT matches to remove FPs due to:
  * samples published on `iban.com` - that meant I had to find a rarer test set!
  * hex strings such as `FE00 0000 0000 0001`
  * examples with all zeros, such as `GB00 0000 0000 0000 0000`
* changed the 'end/after' match pattern so that it doesn't stop early on space-separated patterns. I don't let it end on ` [A-Z0-9]`, which was causing it to match on partial IBANs
* tested at the CLI with my script
* tested in the GUI, with a dry-run
* `README.md` generated

That should make this much more usable. I crammed all of the NOT matches into the allowed 5 additional matches, and it works in the GHEC interface.

I think this is ready to merge!

**Comment by NickLiffen** [comment]
@aegilops great work! Without going through every single one, you get a 👍 from me taking a peek 👀

**Review by aegilops — APPROVED** [review]
I made extensive changes, and tested them offline and in the Secret Scanning interface. It all looks fine to me and Nick Liffen eyeballed it too, finding no issues. I'm good to merge now, and will mop up any changed in a future PR.

I know I could do more to improve the per-country IBAN patterns, based on some of the changes I made to the generic one, but I'm happy to merge anyhow since they are a nice-to-have and not essential for this PR anyhow

**Pull request merged**
